# Generated by Django 4.1.1 on 2022-10-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_att_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.attendant', verbose_name='Acudiente')),
                ('sa_stu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.student', verbose_name='Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='attendant',
            name='stu_id',
            field=models.ManyToManyField(through='personas.Student_Attendant', to='personas.student', verbose_name='Estudiante'),
        ),
    ]
