# Generated by Django 4.1.1 on 2022-10-07 01:43

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_year', models.DateField(verbose_name='Año')),
                ('reg_value', models.FloatField(verbose_name='Valor')),
                ('reg_course', models.CharField(max_length=10, verbose_name='Curso')),
                ('reg_group', models.CharField(max_length=4, verbose_name='Grupo')),
                ('regist_status_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regist_status_type', to='ajustes.datosmaestros', verbose_name='Estado de matrícula')),
                ('school_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_level', to='ajustes.datosmaestros', verbose_name='Nivel escolar')),
                ('stu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.student', verbose_name='Estudiante')),
                ('student_history_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_history_type', to='ajustes.datosmaestros', verbose_name='Histórico de estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(verbose_name='Fecha de pago')),
                ('pay_value', models.FloatField(verbose_name='Valor')),
                ('pay_discount', models.FloatField(verbose_name='Descuento')),
                ('pay_month', multiselectfield.db.fields.MultiSelectField(choices=[('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre')], max_length=200, verbose_name='Mes a pagar')),
                ('pay_total_value', models.FloatField(verbose_name='Valor Total')),
                ('item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='ajustes.datosmaestros', verbose_name='Concepto')),
                ('payment_method_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_type', to='ajustes.datosmaestros', verbose_name='Método de Pago')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='ajustes.datosmaestros', verbose_name='Tipo de Pago')),
                ('reg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.registration', verbose_name='Matrícula')),
            ],
        ),
    ]
